---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-insani-go
  labels:
    svc: svc-insani-go
    tier: backend
  namespace: hcm-stag
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: svc-insani-go
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        svc: svc-insani-go
        tier: backend
    spec:
      imagePullSecrets:
        - name: gcr-uii-key
      containers:
        - name: svc-insani-go
          image: asia.gcr.io/uii-cloud-project/hcm/backend/svc-insani-go:stag
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 128Mi
          ports:
            - name: http-api
              containerPort: 80
          env:
            - name: ENV
              value: "staging"
            - name: SERVICE_NAME
              value: "svc-insani-go"
            - name: APP_DEBUG
              value: "true"
            - name: DBMS
              value: "mysql"
            - name: DB_USER
              value: "sholichin"
            - name: DB_PASSWORD
              value: "bismillahstaging123"
            - name: DB_HOST
              value: "dbstaging.bsi.io"
            - name: DB_PORT
              value: "6033"
            - name: DB_NAME
              value: "hcm_insani"
            - name: DB_MAX_OPEN_CONNECTION
              value: "10"
            - name: DB_MAX_IDLE_CONNECTION
              value: "5"
            - name: DB_MAX_CONNECTION_LIFETIME
              value: "300s"
            - name: MINIO_ENDPOINT
              value: "s3-staging.uii.ac.id"
            - name: MINIO_ACCESSKEYID
              value: "2m8mYMxUUTwTwCqPgy2F"
            - name: MINIO_SECRETACCESSKEY
              value: "6yxf3LPgy4kMNLpKAACe9PzzeS5mJU8cKWA5PwVu"
            - name: MINIO_SSL
              value: "false"
            - name: MINIO_BUCKETNAME
              value: "insani"
            - name: MINIO_LOCATION
              value: "us-east-1"
            - name: MINIO_CONN_TIMEOUT
              value: "10s"
            - name: MINIO_EXPIRATION_SECOND
              value: "36000"
            - name: RESPONSE_TIMEOUT_MS
              value: "13000"
            - name: SLACK_WEBHOOK_URL
              value: "https://hooks.slack.com/services/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"
            - name: URL_HCM_SIMPEG_SERVICE
              value: "http://svc-simpeg-ora-lumen.hcm-stag.svc.cluster.local"
            - name: URL_V2_PRESENCE_SERVICE
              value: "http://svc-presence-lumen.hcm-stag.svc.cluster.local"
            - name: URL_ACTIVATION_PERSONAL
              value: "http://svc-personal-go.hcm-stag.svc.cluster.local"
            - name: URL_HCM_TANGGUNGAN
              value: "http://svc-dependents-go.hcm-stag.svc.cluster.local/public/api/v1/tanggungan-private"

---
apiVersion: v1
kind: Service
metadata:
  name: svc-insani-go
  labels:
    svc: svc-insani-go
    tier: backend
  namespace: hcm-stag
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  svc-insani-go-mapping
      prefix: /v1/insani
      rewrite: /public/api/v1
      service: svc-insani-go.hcm-stag
      timeout_ms: 50000
spec:
  selector:
    svc: svc-insani-go
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    svc: svc-insani-go
    tier: backend
  name: svc-insani-go
  namespace: hcm-stag
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: svc-insani-go
  targetCPUUtilizationPercentage: 50
